sudo: false
language: node_js
node_js:
  - '10'
install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - travis_retry npm install
script:
  - npm run test
  - npm run package
after_success:
  - npm i codecov && codecov
after_failure:
  - cat /home/travis/.npm/_logs/*.log
deploy:
  provider: script
  script: npm run travis-publish
  skip_cleanup: true
  on:
    tags: true
