sudo: false
language: node_js
node_js:
  - '10'
install:
  - npm install
script:
  - npm run ci
  - npm run package
after_success:
  - npm i codecov && codecov
deploy:
  provider: script
  script: npm run travis-publish
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: VFaMHu3I/333C3/DNA18ZIsUw201SGNt6wC2SwGfHEnQHCVJbh+KkwJX/A1Nv/KpJR4CJS2GWKqlXeNQjm03kwad5/+egadkShYUwy5SyGJp8ZHmyZo9RnNHKqSMxs36MHh5zUPg8zxaDY5pafxmu/EXfA4Cl1rFAj0WaZgUYOAX+LyrCzAYHtW7+o7XLLIs+epTcuQFAv1FcoNF0VRPkEhDaO6sfqiTokbgjY5Jr3ceKniA7vLKTGJNe69nBJ2bR45bk6IwDPhYWDODsdqd5xtpcFP4cH5nTS7bwYar60VgqVN5KwKEs0MeydQvsWBFnQj/9ZoMk72O52yUIXo18y0tMmHU2YmXCBrck+2xCdlIpEM65BPQNpmFtJCTo/TsGLcwp1n3fd5GH6I40v85HuomZqxmugsYtOQFkspu1XiS/4KFmmOItCHswCDDlPr67zcgZKPWUMvxSak7wJxM50Hh5n84/UtqlKfc+6wB+Z+7HiVUKEuIHY17A2xJQPexhDqq+Nrw9WXguK3eNKAPq4dr6gD+DzyMyrhUJigzRdIHXDm3CbEIQpXCSYf1NSigNk5XgWscQb+NezvfboVQpYEJxfe1RPe44rCWvzgDKxebxIdaYxNasr1ic4Zzodapya6VAtJu1gg27mXSCqx30QKMwpkJpBReG4ZKGAx0Z+M=
